#!/usr/bin/env python3
"""Create a publishable Sage API index without builder-local source paths.

The full index is intentionally supplied as a release sidecar rather than
checked into the plugin source tree.  Documentation generated by Sage can
contain lines such as ``File: /home/.../sage/foo.py``.  They are useful while
debugging the generator, but must not enter a distributed artifact.  This
tool keeps the portable ``sage/...`` suffix and rejects any remaining common
host-local path after sanitization.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any


FILE_PATH = re.compile(r"(?P<label>\bFile:\s+)(?P<path>(?:[A-Za-z]:[\\/]|/)[^\r\n]*)")
# The negative lookbehind deliberately excludes URL path components such as
# https://example.org/work/foo while still matching a filesystem path after
# whitespace, punctuation, or at the beginning of a string.
HOST_ROOT = r"(?:(?<![A-Za-z0-9])[A-Za-z]:[\\/]|(?<![A-Za-z0-9.-])/(?:home|users|private|tmp|var|opt|workspace|work|mnt|media|volumes|usr/local)/)"
HOST_PATH = re.compile(
    HOST_ROOT,
    re.IGNORECASE,
)
HOST_PATH_VALUE = re.compile(
    rf"(?P<path>{HOST_ROOT}[^\s'\"\x60\)\]\}},;]*)",
    re.IGNORECASE,
)


def portable_path(path: str) -> str:
    normalized = path.replace("\\", "/")
    marker = "/sage/"
    if marker in normalized:
        return "sage/" + normalized.split(marker, 1)[1]
    return "<redacted builder path>"


def sanitize_text(value: str) -> str:
    file_sanitized = FILE_PATH.sub(
        lambda match: match.group("label") + portable_path(match.group("path")),
        value,
    )
    return HOST_PATH_VALUE.sub(
        lambda match: portable_path(match.group("path")),
        file_sanitized,
    )


def sanitize(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: sanitize(child) for key, child in value.items()}
    if isinstance(value, list):
        return [sanitize(child) for child in value]
    if isinstance(value, str):
        return sanitize_text(value)
    return value


def find_host_path(value: Any) -> str | None:
    if isinstance(value, dict):
        for key, child in value.items():
            found = find_host_path(child)
            if found:
                return f"{key}: {found}"
    elif isinstance(value, list):
        for child in value:
            found = find_host_path(child)
            if found:
                return found
    elif isinstance(value, str):
        match = HOST_PATH.search(value)
        if match:
            return value[max(0, match.start() - 24) : match.end() + 96]
    return None


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="full generated Sage API index")
    parser.add_argument("--output", type=Path, required=True, help="sanitized index output path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    with args.input.open(encoding="utf-8") as stream:
        index = json.load(stream)
    if not isinstance(index, dict) or index.get("schemaVersion") != 1:
        raise ValueError("input is not a schemaVersion 1 Sage API index")

    sanitized = sanitize(index)
    remaining = find_host_path(sanitized)
    if remaining:
        raise ValueError(f"unsanitized host-local path remains in release index: {remaining!r}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as stream:
        json.dump(sanitized, stream, ensure_ascii=False, separators=(",", ":"))
        stream.write("\n")
    print(json.dumps({
        "output": str(args.output),
        "sha256": sha256(args.output),
        "sageVersion": sanitized.get("sageVersion"),
        "pythonVersion": sanitized.get("pythonVersion"),
        "entryCount": len(sanitized.get("entries", [])),
    }, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
