package com.starnotesxj.sageide.sugar

import com.intellij.codeInsight.template.postfix.templates.PostfixTemplateProvider

// GENERATED by tools/gen-wrap-template-classes.ps1 — do not edit by hand.
//
// Each Sage call-wrap key gets its own class so the settings preview
// resources resolve per-key (postfixTemplates/<SimpleClassName>/).  A single
// shared class would render the $key placeholder with the dot-prefixed key
// and the preview would show an extra dot in the after state (.CC(expr)).

class SageZZPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("ZZ", provider)

class SageQQPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("QQ", provider)

class SageRRPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("RR", provider)

class SageCCPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("CC", provider)

class SageSRPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("SR", provider)

class SageIntegerPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("Integer", provider)

class SageNPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("N", provider)

class SageFactorPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("factor", provider)

class SageShowPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("show", provider)

class SageVectorPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("vector", provider)

class SageMatrixPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("matrix", provider)

class SageEulerPhiPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("euler_phi", provider)

class SageCarmichaelLambdaPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("carmichael_lambda", provider)

class SageDivisorsPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("divisors", provider)

class SageNumberOfDivisorsPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("number_of_divisors", provider)

class SagePrimeFactorsPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("prime_factors", provider)

class SageSquarefreePartPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("squarefree_part", provider)

class SageNextPrimePostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("next_prime", provider)

class SageRandomPrimePostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("random_prime", provider)

class SagePrimitiveRootPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("primitive_root", provider)

class SageFactorialPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("factorial", provider)

class SageNumeratorPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("numerator", provider)

class SageDenominatorPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("denominator", provider)

class SageContinuedFractionPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("continued_fraction", provider)

class SageCyclotomicPolynomialPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("cyclotomic_polynomial", provider)

class SageSageEvalPostfixTemplate(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate("sage_eval", provider)
