#requires -Version 5.1
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [ValidateScript({ Test-Path -LiteralPath $_ -PathType Leaf })]
  [string] $Installer,
  [Parameter(Mandatory = $true)]
  [string] $InstallRoot,
  [string] $ConfigFile,
  [string] $LogFile,
  [ValidateSet('sage64.exe', 'sage.exe')]
  [string] $ExpectedLauncher = 'sage64.exe',
  [switch] $KeepInstall
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Invoke-WaitingProcess([string] $FilePath, [string[]] $Arguments) {
  $process = Start-Process -FilePath $FilePath -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
  if ($process.ExitCode -ne 0) {
    throw "Process failed with exit code $($process.ExitCode): $FilePath $($Arguments -join ' ')"
  }
  return $process.ExitCode
}

function Wait-PathGone([string] $Path, [int] $Attempts = 80) {
  for ($i = 0; $i -lt $Attempts; $i++) {
    if (-not (Test-Path -LiteralPath $Path)) { return }
    Start-Sleep -Milliseconds 250
  }
  throw "Path still exists after uninstall timeout: $Path"
}

$installerPath = (Resolve-Path -LiteralPath $Installer).Path
$installPath = [IO.Path]::GetFullPath($InstallRoot)
if ($installPath -match '\s') {
  throw "InstallRoot must not contain whitespace because the generated NSIS /D contract requires an unquoted final argument: $installPath"
}
if (Test-Path -LiteralPath $installPath) {
  throw "InstallRoot must not exist before the smoke test: $installPath"
}
$installParent = Split-Path -Parent $installPath
New-Item -ItemType Directory -Force -Path $installParent | Out-Null

$workPath = Join-Path $installParent (".sage-math-installer-smoke-" + [Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $workPath | Out-Null
$configPath = if ($ConfigFile) { (Resolve-Path -LiteralPath $ConfigFile).Path } else { Join-Path $workPath 'silent.config' }
$logPath = if ($LogFile) { [IO.Path]::GetFullPath($LogFile) } else { Join-Path $workPath 'install.log' }

if ($ConfigFile -and -not (Test-Path -LiteralPath $configPath -PathType Leaf)) {
  throw "Silent config does not exist: $configPath"
}
if (-not $ConfigFile) {
  @(
    '; Generated by windows-installer-smoke.ps1; keys match the upstream NSIS parser.',
    'mode=user',
    'launcher64=0',
    'updatePATH=0',
    'updateContextMenu=0'
  ) | Set-Content -LiteralPath $configPath -Encoding ASCII
}
if (-not (Test-Path -LiteralPath $configPath -PathType Leaf)) {
  throw "Silent config does not exist: $configPath"
}
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $logPath) | Out-Null

$report = [ordered]@{
  installer = $installerPath
  installRoot = $installPath
  config = $configPath
  log = $logPath
  launcher = $ExpectedLauncher
  installerExitCode = $null
  uninstaller = $null
  uninstallerExitCode = $null
  installed = $false
  uninstalled = $false
}

try {
  # NSIS requires /D=<install-dir> to be the final command-line argument.
  # InstallRoot is intentionally whitespace-free, so avoid Start-Process quote
  # reconstruction and pass the switches as literal unquoted assignments.
  $installerArgs = @(
    '/S',
    ('/CONFIG={0}' -f $configPath),
    ('/LOG={0}' -f $logPath),
    ('/D={0}' -f $installPath)
  )
  $report.installerExitCode = Invoke-WaitingProcess $installerPath $installerArgs

  $launcherPath = Join-Path $installPath "bin/$ExpectedLauncher"
  $uninstallerPath = Join-Path $installPath 'bin/Uninstall.exe'
  $pluginPath = $null
  $pluginBase = Join-Path $installPath 'plugins'
  if (Test-Path -LiteralPath $pluginBase -PathType Container) {
    foreach ($pluginDir in @(Get-ChildItem -LiteralPath $pluginBase -Directory -ErrorAction SilentlyContinue)) {
      if ($pluginDir.Name -match '(?i)sage.*core') {
        $candidate = Join-Path $pluginDir.FullName 'lib'
        if (Test-Path -LiteralPath $candidate -PathType Container) {
          $pluginPath = $candidate
          break
        }
      }
    }
  }
  if (-not (Test-Path -LiteralPath $launcherPath -PathType Leaf)) {
    throw "Installed launcher is missing: $launcherPath"
  }
  if (-not (Test-Path -LiteralPath $uninstallerPath -PathType Leaf)) {
    throw "Installed uninstaller is missing: $uninstallerPath"
  }
  if (-not $pluginPath -or -not (Get-ChildItem -LiteralPath $pluginPath -Filter '*.jar' -File -ErrorAction SilentlyContinue)) {
    throw "Bundled Sage Core plugin JARs are missing under: $pluginBase"
  }
  $report.installed = $true
  $report.uninstaller = $uninstallerPath
  $report.sageCorePlugin = $pluginPath

  $launchProcess = Start-Process -FilePath $launcherPath -WorkingDirectory (Split-Path -Parent $launcherPath) -PassThru
  $report.launchProcessId = $launchProcess.Id
  Start-Sleep -Seconds 15
  $runningInstalledProcesses = @(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
    $_.ExecutablePath -and $_.ExecutablePath.StartsWith($installPath, [StringComparison]::OrdinalIgnoreCase)
  })
  if ($launchProcess.HasExited -and $runningInstalledProcesses.Count -eq 0) {
    throw "Installed launcher exited without leaving a product process: $launcherPath"
  }
  $report.launched = $true
  foreach ($process in $runningInstalledProcesses) {
    Stop-Process -Id $process.ProcessId -Force -ErrorAction SilentlyContinue
  }
  if (-not $launchProcess.HasExited) {
    Stop-Process -Id $launchProcess.Id -Force -ErrorAction SilentlyContinue
  }

  # This /S switch is the generated QuietUninstallString from the NSIS script.
  $report.uninstallerExitCode = Invoke-WaitingProcess $uninstallerPath @('/S')
  Wait-PathGone $installPath
  $report.uninstalled = $true
  $report | ConvertTo-Json -Depth 5
}
finally {
  if (-not $KeepInstall) {
    Remove-Item -LiteralPath $installPath -Recurse -Force -ErrorAction SilentlyContinue
  }
  Remove-Item -LiteralPath $workPath -Recurse -Force -ErrorAction SilentlyContinue
}
