#requires -Version 5.1
[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][ValidateScript({Test-Path -LiteralPath $_ -PathType Container})][string]$ArtifactsRoot,
  [ValidateSet('x64','arm64','all')][string]$Architecture='all',
  [string]$DistributionRoot,
  [string]$SourceLegalRoot,
  [string]$JsonOutput,
  [string]$MarkdownOutput,
  [switch]$FailOnFindings
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$root=(Resolve-Path -LiteralPath $ArtifactsRoot).Path
if(!$DistributionRoot){$DistributionRoot=$root}; $DistributionRoot=(Resolve-Path -LiteralPath $DistributionRoot).Path
if(!$SourceLegalRoot){$SourceLegalRoot=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '../../..')).Path}; $SourceLegalRoot=(Resolve-Path -LiteralPath $SourceLegalRoot).Path
$findings=[Collections.Generic.List[object]]::new()
function Add-Finding([string]$Severity,[string]$Code,[string]$Message,[string]$Path){$x=[ordered]@{severity=$Severity;code=$Code;message=$Message};if($Path){$x.path=$Path};[void]$findings.Add([pscustomobject]$x)}
function HashSidecar([string]$File,[string]$Algorithm){$side="$File.$($Algorithm.ToLowerInvariant())";$name=[IO.Path]::GetFileName($File);if(!(Test-Path -LiteralPath $side -PathType Leaf)){Add-Finding Warning HASH_SIDECAR_MISSING "$Algorithm sidecar missing" $side;return [ordered]@{passed=$false;sidecar=$side}};$line=Get-Content -LiteralPath $side|Where-Object{$_.Trim()}|Select-Object -First 1;if($line -notmatch '^\s*([0-9a-fA-F]+)\s+[*]?(.+?)\s*$'){Add-Finding Error HASH_SIDECAR_INVALID "$Algorithm sidecar format invalid" $side;return [ordered]@{passed=$false;sidecar=$side}};$expected=$Matches[1].ToLowerInvariant();$actual=(Get-FileHash -LiteralPath $File -Algorithm $Algorithm).Hash.ToLowerInvariant();$named=([IO.Path]::GetFileName($Matches[2].Trim()) -eq $name);$ok=($expected -eq $actual -and $named);if(!$ok){Add-Finding Error HASH_MISMATCH "$Algorithm does not match sidecar" $File};return [ordered]@{passed=$ok;expected=$expected;actual=$actual;sidecar=$side}}
function Signature([string]$File){try{$s=Get-AuthenticodeSignature -LiteralPath $File;$r=[ordered]@{status=[string]$s.Status;statusMessage=[string]$s.StatusMessage;isSigned=[bool]$s.SignerCertificate;signer=if($s.SignerCertificate){$s.SignerCertificate.Subject}else{$null};thumbprint=if($s.SignerCertificate){$s.SignerCertificate.Thumbprint}else{$null}};if([string]$s.Status -ne 'Valid'){Add-Finding Warning AUTHENTICODE_NOT_VALID "Authenticode status: $($s.Status)" $File};return $r}catch{Add-Finding Warning AUTHENTICODE_UNAVAILABLE $_.Exception.Message $File;return [ordered]@{status='Unavailable';isSigned=$false;error=$_.Exception.Message}}}
$specs=@([ordered]@{arch='x64';installer='sageMath-263.SNAPSHOT.exe';uninstaller='Uninstall-SMC-amd64.exe';archive='sageMath-263.SNAPSHOT.win.zip'},[ordered]@{arch='arm64';installer='sageMath-263.SNAPSHOT-aarch64.exe';uninstaller='Uninstall-SMC-aarch64.exe';archive='sageMath-263.SNAPSHOT-aarch64.win.zip'})|Where-Object{$Architecture -eq 'all' -or $_.arch -eq $Architecture}
$rows=@()
foreach($s in $specs){$row=[ordered]@{architecture=$s.arch};foreach($kind in @('installer','uninstaller')){$file=Join-Path $root $s[$kind];if(!(Test-Path -LiteralPath $file -PathType Leaf)){Add-Finding Error ARTIFACT_MISSING "$kind missing" $file;continue};$x=[ordered]@{path=$file;signature=Signature $file};if($kind -eq 'installer' -or $kind -eq 'uninstaller'){$x.sha256=HashSidecar $file 'SHA256';$x.sha512=HashSidecar $file 'SHA512'};$row[$kind]=$x};$archive=Join-Path $root $s.archive;if(Test-Path -LiteralPath $archive -PathType Leaf){$row.archive=[ordered]@{path=$archive;sha256=HashSidecar $archive 'SHA256';sha512=HashSidecar $archive 'SHA512'}}else{Add-Finding Error ARTIFACT_MISSING "Windows archive missing" $archive};$rows+=[pscustomobject]$row}
function First([string[]]$Names,[string]$Base){foreach($n in $Names){$p=Join-Path $Base $n;if(Test-Path -LiteralPath $p -PathType Leaf){return (Resolve-Path $p).Path};$m=Get-ChildItem -LiteralPath $Base -Recurse -File -Filter $n -ErrorAction SilentlyContinue|Select-Object -First 1;if($m){return $m.FullName}};return $null}
$spdx=@(Get-ChildItem -LiteralPath $root -File -Filter '*.spdx.json'|% FullName);$third=First @('sageMath-263.SNAPSHOT-third-party-libraries.json') $root;$thirdHtml=First @('sageMath-263.SNAPSHOT-third-party-libraries.html') $root;$deps=First @('dependencies.txt') $root;$sources=First @('sageMath-263.SNAPSHOT-sources.zip') $root;$prod=@(Get-ChildItem -LiteralPath $root -File -Filter '*.product-info.json'|% FullName)
foreach($v in @(@('product-info',$prod),@('SPDX',$spdx),@('third-party',$third),@('third-party-html',$thirdHtml),@('dependencies',$deps),@('sources',$sources))){if(($v[1] -is [array] -and !$v[1].Count)-or($v[1] -isnot [array] -and !$v[1])){Add-Finding Error LEGAL_ARTIFACT_MISSING "$($v[0]) missing" $root}}
$packages=0;foreach($p in $spdx){try{$d=Get-Content $p -Raw|ConvertFrom-Json;$packages+=@($d.packages).Count;if(!$d.spdxVersion-or !$d.packages){Add-Finding Error SPDX_INVALID 'SPDX missing version/packages' $p};if($d.comment -match 'work in progress'){Add-Finding Warning SPDX_WORK_IN_PROGRESS 'SPDX says work in progress' $p};$n=@($d.packages|?{$_.licenseDeclared -eq 'NOASSERTION'-or$_.licenseConcluded -eq 'NOASSERTION'}).Count;if($n){Add-Finding Warning SPDX_NOASSERTION "$n packages contain NOASSERTION" $p}}catch{Add-Finding Error SPDX_PARSE_FAILED $_.Exception.Message $p}}
if($third){try{if(!(@(Get-Content $third -Raw|ConvertFrom-Json).Count)){Add-Finding Error THIRD_PARTY_EMPTY 'third-party list empty' $third}}catch{Add-Finding Error THIRD_PARTY_PARSE_FAILED $_.Exception.Message $third}}
$sl=First @('LICENSE','LICENSE.txt','LICENSE.md') $SourceLegalRoot;$sn=First @('NOTICE','NOTICE.txt','NOTICE.md') $SourceLegalRoot;$dl=First @('LICENSE','LICENSE.txt','LICENSE.md') $DistributionRoot;$dn=First @('NOTICE','NOTICE.txt','NOTICE.md') $DistributionRoot
if(!$sl){Add-Finding Error SOURCE_LICENSE_MISSING 'source LICENSE missing' $SourceLegalRoot};if(!$sn){Add-Finding Error SOURCE_NOTICE_MISSING 'source NOTICE missing' $SourceLegalRoot};if(!$dl){Add-Finding Warning DISTRIBUTION_LICENSE_MISSING 'distribution LICENSE not found; verify installed payload' $DistributionRoot};if(!$dn){Add-Finding Warning DISTRIBUTION_NOTICE_MISSING 'distribution NOTICE not found; verify installed payload' $DistributionRoot}
$report=[ordered]@{schemaVersion='1.0';generatedAtUtc=[DateTime]::UtcNow.ToString('o');readOnly=$true;buildInvoked=$false;artifactsRoot=$root;architecture=$Architecture;artifacts=$rows;staticAudit=[ordered]@{productInfo=$prod;spdx=$spdx;spdxPackageCount=$packages;thirdParty=$third;thirdPartyHtml=$thirdHtml;dependencies=$deps;sources=$sources;license=[ordered]@{source=$sl;distribution=$dl};notice=[ordered]@{source=$sn;distribution=$dn}};findings=@($findings)};$report.summary=[ordered]@{errors=@($findings|? severity -eq Error).Count;warnings=@($findings|? severity -eq Warning).Count;passed=(!$findings.Count)}
$json=$report|ConvertTo-Json -Depth 12;$md=@('# Windows release audit','',"- Result: $($(if($report.summary.passed){'PASS'}else{'FINDINGS'}))","- Root: $root","- Architecture: $Architecture","- Errors: $($report.summary.errors)","- Warnings: $($report.summary.warnings)",'','## Findings','');if(!$findings.Count){$md+='- None'}else{foreach($f in $findings){$md+="- **$($f.severity)** [$($f.code)] $($f.message)"}};$md=$md -join [Environment]::NewLine
if($JsonOutput){$json|Set-Content -LiteralPath $JsonOutput -Encoding UTF8};if($MarkdownOutput){$md|Set-Content -LiteralPath $MarkdownOutput -Encoding UTF8};$json;if($FailOnFindings -and $findings.Count){exit 1}
