# Generates the per-key Sage call-wrap postfix template subclasses and their
# settings-preview resources.
#
# WHY per-key classes: the platform renders the preview from
# postfixTemplates/<SimpleClassName>/before|after.*.template and replaces the
# literal `$key` with the template key VERBATIM — the key is dot-prefixed
# (".ZZ"), so a single shared class with `$key` resources would render
# `expr.CC` / `.CC(expr)` (extra dot in the "after" state).  Per-key classes
# hardcode the plain name instead, exactly like the b2i/i2b resources do.
#
# description.html is also required per key (v1.6.5 fix): the settings preview
# resolves it by <SimpleClassName> as a STATIC resource
# (PostfixTemplateMetaData.getResourceLocation) — the template's overridden
# getDescription() method is never consulted by PostfixDescriptionPanel, and a
# missing description.html raises a SEVERE "Resource not found" per click.
#
# Re-run this script whenever SAGE_WRAPPERS changes in
# SagePostfixTemplateProvider.kt, then update the provider's sageTemplates to
# use the generated classes.

$keys = @(
  "ZZ", "QQ", "RR", "CC", "SR", "Integer", "N",
  "factor", "show", "vector", "matrix",
  "euler_phi", "carmichael_lambda", "divisors", "number_of_divisors",
  "prime_factors", "squarefree_part", "next_prime", "random_prime",
  "primitive_root", "factorial", "numerator", "denominator",
  "continued_fraction", "cyclotomic_polynomial", "sage_eval"
)

$root = "G:\Projects\sage-ide-support"
$kt = Join-Path $root "src\main\kotlin\com\starnotesxj\sageide\sugar\SageCallWrapPostfixTemplates.kt"
$res = Join-Path $root "src\main\resources\postfixTemplates"

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("package com.starnotesxj.sageide.sugar")
$lines.Add("")
$lines.Add("import com.intellij.codeInsight.template.postfix.templates.PostfixTemplateProvider")
$lines.Add("")
$lines.Add("// GENERATED by tools/gen-wrap-template-classes.ps1 — do not edit by hand.")
$lines.Add("//")
$lines.Add("// Each Sage call-wrap key gets its own class so the settings preview")
$lines.Add("// resources resolve per-key (postfixTemplates/<SimpleClassName>/).  A single")
$lines.Add("// shared class would render the `$key placeholder with the dot-prefixed key")
$lines.Add("// and the preview would show an extra dot in the after state (`.CC(expr)`).")

foreach ($key in $keys) {
  $pascal = (($key -split '_') | ForEach-Object {
    $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1)
  }) -join ''
  $cls = "Sage${pascal}PostfixTemplate"
  $lines.Add("")
  $lines.Add("class $cls(provider: PostfixTemplateProvider) : SageCallWrapPostfixTemplate(`"$key`", provider)")

  $dir = Join-Path $res $cls
  New-Item -ItemType Directory -Force $dir | Out-Null
  [System.IO.File]::WriteAllText((Join-Path $dir "before.py.template"), "<spot>expr</spot>.$key")
  [System.IO.File]::WriteAllText((Join-Path $dir "after.py.template"), "$key(<spot>expr</spot>)")
  $desc = @"
<html>
<body>
用 <code>sage.all</code> 的 <code>$key(expr)</code> 包裹所选表达式（<code>.sage</code> 文件中无需导入）。
</body>
</html>
"@
  [System.IO.File]::WriteAllText((Join-Path $dir "description.html"), $desc)
}

[System.IO.File]::WriteAllLines($kt, $lines)
"Generated: $($keys.Count) classes + $($keys.Count * 3) resource files"
